import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
    './context/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      // Marketing site Material Design 3 color tokens (from index.html)
      colors: {
        'on-tertiary-fixed': '#331018',
        'primary-fixed-dim': '#ffb2b9',
        'on-error-container': '#ffdad6',
        'on-tertiary': '#4c242c',
        'surface': '#141313',
        'surface-container': '#211f1f',
        'primary-container': '#ff5473',
        'secondary': '#ffb59e',
        'on-surface-variant': '#e1bec0',
        'surface-variant': '#363434',
        'tertiary': '#f4b7c0',
        'secondary-container': '#7f2a0d',
        'surface-container-lowest': '#0f0e0e',
        'primary': '#ffb2b9',
        'on-primary': '#67001f',
        'inverse-on-surface': '#323030',
        'surface-dim': '#141313',
        'tertiary-fixed-dim': '#f4b7c0',
        'surface-bright': '#3a3939',
        'on-tertiary-fixed-variant': '#663a42',
        'on-secondary-container': '#ff9b7c',
        'primary-fixed': '#ffdadc',
        'on-surface': '#e6e1e1',
        'surface-container-highest': '#363434',
        'on-primary-fixed-variant': '#91002f',
        'surface-container-high': '#2b2a29',
        'on-primary-container': '#5d001b',
        'on-error': '#690005',
        'secondary-fixed-dim': '#ffb59e',
        'outline-variant': '#5a4042',
        'on-primary-fixed': '#400010',
        'outline': '#a9898b',
        'on-background': '#e6e1e1',
        'surface-tint': '#ffb2b9',
        'inverse-surface': '#e6e1e1',
        'error': '#ffb4ab',
        'tertiary-fixed': '#ffd9de',
        'on-tertiary-container': '#461f27',
        'surface-container-low': '#1c1b1b',
        'background': '#141313',
        'inverse-primary': '#b71b43',
        'tertiary-container': '#bb848d',
        'secondary-fixed': '#ffdbd0',
        'on-secondary-fixed-variant': '#7f2a0d',
        'on-secondary-fixed': '#3a0b00',
        'error-container': '#93000a',
        'on-secondary': '#5e1700',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
